
###
// 1__ registra usuario
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name":"Enrique",
    "lastName":"Abramzon",
    "email":"eabramzon@gmail.com",
    "password":"1234"
}

###
// 2__ postea a ruta login y recibe el token
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"eabramzon@gmail.com",
    "password":"1234"
}


###
// ruta a list de actores con el token recibido
GET http://localhost:3000/characters
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJuYW1lIjoiRW5yaXF1ZSIsImxhc3ROYW1lIjoiQWJyYW16b24iLCJlbWFpbCI6ImVhYnJhbXpvbkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCQuZmc1TkNkNjF3bVJTYVVmTFZGVFEudGtzUWg5NGdFVlBnWnkyTGtybzM5Mm0uL3pLVHljRyIsImNyZWF0ZWRBdCI6IjIwMjEtMDktMDNUMTc6NTk6NTAuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDktMDNUMTc6NTk6NTAuMDAwWiJ9LCJpYXQiOjE2MzA2OTIyNzEsImV4cCI6MTYzMTU1NjI3MX0.ujf1Bxbu7at9Cb9plaaJ7Keu5pIGegbu-9vvpa5PLcM

###
// crear pelicula
POST http://localhost:3000/movies/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiRW5yaXF1ZSIsImxhc3ROYW1lIjoiQWJyYW16b24iLCJlbWFpbCI6ImVhYnJhbXpvbkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCR6eUtvRXh2aHhSaDFLcVhlakxEWEhlQ1NaU3p0T1hxWHpaM2xpcGNJREpWWjNGbkJMNVRadSIsImNyZWF0ZWRBdCI6IjIwMjEtMDktMDJUMjA6MjU6MDkuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDktMDJUMjA6MjU6MDkuMDAwWiJ9LCJpYXQiOjE2MzA2MTQzNTksImV4cCI6MTYzMTQ3ODM1OX0.lLoXhhxywkhVybnAEGRa3KSdOUal78G45UxH1kXiLow

{
    "genreId":"2",
    "title":"OuijaIII",
    "image":"https://es.web.img3.acsta.net/pictures/16/06/27/12/51/126212.jpg",
    "stars":"1"
}

###
// 7__ Listado de Películas Deberá mostrar solamente los campos imagen, título y fecha de creación.El endpoint deberá ser:● GET /movies
GET http://localhost:3000/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJuYW1lIjoiRW5yaXF1ZSIsImxhc3ROYW1lIjoiQWJyYW16b24iLCJlbWFpbCI6ImVhYnJhbXpvbkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCQuZmc1TkNkNjF3bVJTYVVmTFZGVFEudGtzUWg5NGdFVlBnWnkyTGtybzM5Mm0uL3pLVHljRyIsImNyZWF0ZWRBdCI6IjIwMjEtMDktMDNUMTc6NTk6NTAuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDktMDNUMTc6NTk6NTAuMDAwWiJ9LCJpYXQiOjE2MzA2OTIyNzEsImV4cCI6MTYzMTU1NjI3MX0.ujf1Bxbu7at9Cb9plaaJ7Keu5pIGegbu-9vvpa5PLcM

###
// 8__ Detalle de Película / Serie con sus personajes
GET http://localhost:3000/movies/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiRW5yaXF1ZSIsImxhc3ROYW1lIjoiQWJyYW16b24iLCJlbWFpbCI6ImVhYnJhbXpvbkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCR6eUtvRXh2aHhSaDFLcVhlakxEWEhlQ1NaU3p0T1hxWHpaM2xpcGNJREpWWjNGbkJMNVRadSIsImNyZWF0ZWRBdCI6IjIwMjEtMDktMDJUMjA6MjU6MDkuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDktMDJUMjA6MjU6MDkuMDAwWiJ9LCJpYXQiOjE2MzA2MTQzNTksImV4cCI6MTYzMTQ3ODM1OX0.lLoXhhxywkhVybnAEGRa3KSdOUal78G45UxH1kXiLow


###
// 8__ Detalle de genero / con pelis asociadas
GET http://localhost:3000/genres/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiRW5yaXF1ZSIsImxhc3ROYW1lIjoiQWJyYW16b24iLCJlbWFpbCI6ImVhYnJhbXpvbkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCR6eUtvRXh2aHhSaDFLcVhlakxEWEhlQ1NaU3p0T1hxWHpaM2xpcGNJREpWWjNGbkJMNVRadSIsImNyZWF0ZWRBdCI6IjIwMjEtMDktMDJUMjA6MjU6MDkuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDktMDJUMjA6MjU6MDkuMDAwWiJ9LCJpYXQiOjE2MzA2MTQzNTksImV4cCI6MTYzMTQ3ODM1OX0.lLoXhhxywkhVybnAEGRa3KSdOUal78G45UxH1kXiLow